### PR TITLE
Composer prep

### PR DESCRIPTION
**Pull request by philwareham**

### CODE REVIEW

**Comment by philwareham** [comment]
Cool. You'll need to now do the following:

1. Go to https://packagist.org, register an account if you haven't already (you can use your GitHub credentials) and then submit your Composer package here: https://packagist.org/packages/submit
2. Follow the instructions at foot of page here https://packagist.org/about to hook the Packagist service into your GitHub repo.
3. Check the Packagist name matches what's in composer.json and amend that file if necessary
4. Tag a release version 1.2.0 (or maybe 1.2.0-beta, but you'd have to amend the version number in plugin and manifest also).

Let me know when above is done, then I'll test it works.

**Comment by Bloke** [comment]
Well, I've done that (I've had a packagist account for years, never used it) but I haven't bundled up the plugin as a `.txt` file because I need to set up a true 4.6.2 environment. My 4.7.0-dev database has all the lang strings altered ready for language-inclusion so Plugin Composer would export Textpacks using the `fr` designator instead of the 4.6.x-friendly `fr-fr`. Do you need the compiled `.txt` files to test it, or does it install from  the `.php` file?

**Comment by philwareham** [comment]
It just uses the PHP. Can you provide the Packagist URL to me?

**Comment by philwareham** [comment]
Actually I've found it and tested installing via Composer. Works fine, thanks.

Hopefully that gives you the bits you need to put Composer support on your other plugins ;) - I think that may become useful when I reimagine the textpattern.org site. Maybe.

**Comment by Bloke** [comment]
Yep, I'll start adding support and publishing them to packagist. Thanks for the nudge.

**Comment by philwareham** [comment]
Nice! Then you can simply add Textpattern plugins to a project like this: https://github.com/textpattern/textpattern-com-website/blob/master/composer.json - so much easier than pasting text into the plugins panel, and all version controlled too.

Now if we can get zem_contact_reborn renamed I'll be a happy bunny.

**Pull request merged**
